apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
  rules:
  - host: www.guestbook-site.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: frontend
          servicePort: 80
